import os
import sys
import numpy as np
import pickle as pkl
import pandas as pd
import seaborn as sns
import scipy.stats as stats
from sklearn import metrics
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
from sklearn.decomposition import PCA as PCA
from sklearn.manifold import TSNE
from sklearn.externals import joblib

class LossPlot():
	""" 
	Uses `matplotlib` and `seaborn` to plot the test loss, 
	generator loss, discriminator loss across several epochs.

	Parameters
	----------
	log_file : string, required
		The pickle file with all the log values generated by
		HealthGAN.
	"""

	def __init__(self, log_file):

		if not os.path.exists('gen_data'):
			os.makedirs('gen_data')

		if not os.path.exists('gen_data/plots'):
			os.makedirs('gen_data/plots')

		try:
			self.log = pkl.load(open(log_file, 'rb'))
		except:
			print("Please provide a correct pickle log file")

	def plot(self, savefig=False):
		"""
		Plot the loss graph.

		Parameters
		----------
		savefig: boolean, optional
			If set to True, the plots generated will be saved to disk.

		Outputs
		-------
		Produces a 8x8 figure for losses
		"""
		losses = ['test_loss', 'gen_loss', 'disc_loss', 'time']
		titles = ['Test Loss', 'Generator Loss', 'Discriminator Loss', 'Time per Epoch']

		pylab.rcParams['figure.figsize'] = 6, 6

		try:
			for i, loss in enumerate(losses):
				j = i%2
				if isinstance(self.log[loss][0], list):
					new_df = pd.DataFrame({titles[i]: [v[-1] for v in self.log[loss]]})
				else:
					new_df = pd.DataFrame({titles[i]: self.log[loss]})
				sns.lineplot(data=new_df, dashes=False, palette="hls")
				plt.title(titles[i])
				plt.xlabel('Epochs (in thousands)')
				if (savefig):
					plt.savefig('gen_data/plots/' + loss + '.png')
				plt.show()
				plt.close()
			if (savefig):
				print("Plots saved! Refer to the files 'time.pdf', test_loss.pdf', 'disc_loss.pdf' and 'gen_loss.pdf' inside 'gen_data/plots' folder.")
		except:
			print("Could not produce plots")


class ComponentPlots():
	""" 
	Uses `matplotlib` and `seaborn` to plot PCA and TSNE plot
	for real and synthetic data files.
	"""

	def __init__(self):

		if not os.path.exists('gen_data'):
			os.makedirs('gen_data')

		if not os.path.exists('gen_data/plots'):
			os.makedirs('gen_data/plots')

	def pca_plot(self,
				 real_data,
				 synthetic_data=None, 
				 title="Two Component PCA",
				 savefig=False):
		""" 
		The function plots PCA between two components for 
		real and synthetic data.

		Parameters
		----------
		real_data : str, required
			The file which contains the real data.
		synthetic_data : str, optional
			The file which contains the synthetic data.
		title: str, optional
			The title of the plot.
		savefig: boolean, optional
			If set to True, the plots generated will be saved to disk.
		  
		Outputs
		-------
		PCA Plot:
			Plots the PCA components for the two datasets and 
			save file with the given name followed by '_real_syn'.
		"""

		real_data = pd.read_csv(real_data)
		if synthetic_data is not None:
			synthetic_data = pd.read_csv(synthetic_data)

		plt.style.use('seaborn-muted')
		pylab.rcParams['figure.figsize'] = 8, 8
		np.random.seed(1234)
		flatui = ["#34495e", "#e74c3c"]
		sns.set_palette(flatui)

		pca_orig = PCA(2)
		pca_orig_data = pca_orig.fit_transform(real_data)
		plt.scatter(*pca_orig_data.T, alpha=.3)

		plt.title(title, fontsize=24)
		plt.xlabel('First Component', fontsize=16)
		plt.ylabel('Second Component', fontsize=16)

		if synthetic_data is not None:
			pca_synth_data = pca_orig.transform(synthetic_data)
			plt.scatter(*pca_synth_data.T, alpha=.4)
			plt.legend(labels=['Original Data', 'Synthetic Data'])
			if (savefig):
				plt.savefig(f'gen_data/plots/{title}_real_syn.png')
			plt.show()
			if (savefig):
				print(f"PCA Plot generated as {title}_real_syn.png inside gen_data/plots.")
		else:
			plt.legend(labels=['Original Data'])
			if (savefig):
				plt.savefig(f'gen_data/plots/{title}_real.png')
			plt.show()
			if (savefig):
				print(f"PCA Plot generated as {title}_real.png inside gen_data/plots.")

	def combined_pca(self,
					 real_data, 
					 synthetic_datas, 
					 names,
					 savefig=False):
		""" 
		The function plots PCA between two components between
		real data and several synthetic datasets.

		Parameters
		----------
		real_data : str, required
			The file which contains the real data.
		synthetic_datas : list, required
			The list of files that contain synthetic data (max 6).
		names: list, required
			The titles for each plot.
		savefig: boolean, optional
			If set to True, the plots generated will be saved to disk.
		  
		Outputs
		-------
		PCA Plots:
			Plots the PCA components across a set of plots for each
			of the synthetic data files.
		"""

		plt.style.use('seaborn-muted')
		pylab.rcParams['figure.figsize'] = 8, 8
		np.random.seed(1234)
		flatui = ["#34495e", "#e74c3c"]
		sns.set_palette(flatui)

		real_data = pd.read_csv(real_data)

		fig, ((ax1, ax2, ax3), (ax4, ax5, ax6)) = plt.subplots(
			2, 3, sharey=True, sharex=True)

		pca_orig = PCA(2)
		pca_orig_data = pca_orig.fit_transform(real_data)

		axes = [ax1, ax2, ax3, ax4, ax5, ax6]

		# plot orig data
		for a in axes:
			a.scatter(*pca_orig_data.T, alpha=.3)

		pca_synth_data = []
		for s in synthetic_datas:
			s = pd.read_csv(s)
			pca_synth_data.append(pca_orig.transform(s))

		for i, a in enumerate(axes):
			if i < len(pca_synth_data):
				a.scatter(*(pca_synth_data[i]).T, alpha=.4)

			a.set_title(names[i], fontsize=16)

		fig.add_subplot(111, frameon=False)

		# Hide tick and tick label of the big axes
		plt.tick_params(labelcolor='none', 
						top='off', 
						bottom='off', 
						left='off', 
						right='off')
		plt.grid(False)
		plt.xlabel("First Component", fontsize=18)
		plt.ylabel("Second Component", fontsize=18)

		if (savefig):
			plt.savefig(f'gen_data/plots/combined_pca.png')
		plt.show()
		if (savefig):
			print(f"PCA Plot generated as combined_pca.png inside gen_data/plots.")

	def combined_tsne(self,
					 real_data, 
					 synthetic_datas, 
					 names,
					 savefig=False):

		""" 
		The function plots t-distributed Stochastic Neighbor Embedding 
		between two components for real and several synthetic datasets.

		Parameters
		----------
		real_data : str, required
			The file which contains the real data.
		synthetic_datas : list, required
			The list of files that contain synthetic data (max 6).
		names: list, required
			The titles for each plot.
		savefig: boolean, optional
			If set to True, the plots generated will be saved to disk.

		Outputs
		-------
		PCA Plots:
			Plots the PCA components across a set of plots for each
			of the synthetic data files.
		"""

		plt.style.use('seaborn-muted')
		pylab.rcParams['figure.figsize'] = 8, 8
		np.random.seed(1234)
		flatui = ["#34495e", "#e74c3c"]
		sns.set_palette(flatui)

		real_data = pd.read_csv(real_data)

		fig, ((ax1, ax2, ax3), (ax4, ax5, ax6)) = plt.subplots(
			2, 3, sharey=True, sharex=True)

		tsne_orig = TSNE(n_components=2)
		tsne_orig_data = tsne_orig.fit_transform(real_data)

		axes = [ax1, ax2, ax3, ax4, ax5, ax6]

		# plot orig data
		for a in axes:
			a.scatter(*tsne_orig_data.T, alpha=.3)

		tsne_synth_data = []
		for s in synthetic_datas:
			s = pd.read_csv(s)
			tsne_synth_data.append(tsne_orig.fit_transform(s))

		for i, a in enumerate(axes):
			if i < len(tsne_synth_data):
				a.scatter(*(tsne_synth_data[i]).T, alpha=.4)

			a.set_title(names[i], fontsize=16)

		fig.add_subplot(111, frameon=False)

		# Hide tick and tick label of the big axes
		plt.tick_params(labelcolor='none', 
						top='off', 
						bottom='off', 
						left='off', 
						right='off')
		plt.grid(False)
		plt.xlabel("First Component", fontsize=18)
		plt.ylabel("Second Component", fontsize=18)

		if (savefig):
			plt.savefig(f'gen_data/plots/combined_tsne.png')
		plt.show()
		if (savefig):
		print(f"PCA Plot generated as combined_tsne.png inside gen_data/plots.")