import sys
import pickle as pkl
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.pylab as pylab
import seaborn as sns

class LossPlot():
    """ 
    Uses `matplotlib` and `seaborn` to plot the test loss, 
    generator loss, discriminator loss across several epochs.

    Parameters
    ----------
    log_file : string, required
        The pickle file with all the log values generated by
        HealthGAN.
    """

    def __init__(self, log_file):
        try:
            self.log = pkl.load(open(log_file, 'rb'))
        except:
            print("Please provide a correct pickle log file")

    def save_plot(self):
        """
        Plot the loss graph.

        Outputs
        -------
        Produces a 8x8 figure for losses
        """
        losses = ['test_loss', 'gen_loss', 'disc_loss', 'time']
        titles = ['Test Loss', 'Generator Loss', 'Discriminator Loss', 'Time per Epoch']
        labels = ['Epochs (in thousands)', 'Epochs', 'Epochs', 'Epochs']

        pylab.rcParams['figure.figsize'] = 8, 8

        try:
            for i, loss in enumerate(losses):
                if isinstance(self.log[loss][0], list):
                    new_df = pd.DataFrame({titles[i]: [v[-1] for v in self.log[loss][100:]]})
                else:
                    new_df = pd.DataFrame({titles[i]: self.log[loss]})
                sns.lineplot(data=new_df, dashes=False, palette="hls")
                plt.title(titles[i])
                plt.xlabel('Epochs (in thousands)')
                plt.savefig(loss + '.pdf')
                plt.close()
            print("Plots generated! Refer to the files 'test_loss.pdf', 'disc_loss.pdf' and 'gen_loss.pdf'")
        except:
            print("Could not produce plots")